services:
  db:
    environment:
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"

  api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=ChubbPolicyManagement;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "5000:5000"
