<#
.SYNOPSIS
    Parses Coverlet OpenCover XML output and appends a timestamped coverage entry
    to coverage-logs/coverage-history.md. Invoked automatically via MSBuild AfterTest target.

.PARAMETER CoverageDir
    Path to the directory containing coverage.opencover.xml files.
    Defaults to the workspace-relative coverage-logs/ folder.
#>
param(
    [string]$CoverageDir = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Resolve paths ────────────────────────────────────────────────────────────
$scriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$workspaceDir = Split-Path -Parent $scriptDir

if ([string]::IsNullOrEmpty($CoverageDir)) {
    $CoverageDir = Join-Path $workspaceDir "coverage-logs"
}

$logFile = Join-Path $workspaceDir "coverage-logs\coverage-history.md"
$summaryFile = Join-Path $workspaceDir "coverage-logs\latest-summary.md"

# ── Find the most recent coverage XML ────────────────────────────────────────
$xmlFiles = Get-ChildItem -Path $CoverageDir -Recurse -Filter "coverage.opencover.xml" -ErrorAction SilentlyContinue

if (-not $xmlFiles -or $xmlFiles.Count -eq 0) {
    # Also scan TestResults directories (dotnet test default)
    $xmlFiles = Get-ChildItem -Path $workspaceDir -Recurse -Filter "coverage.opencover.xml" -ErrorAction SilentlyContinue |
                Where-Object { $_.FullName -notlike "*\obj\*" }
}

if (-not $xmlFiles -or $xmlFiles.Count -eq 0) {
    Write-Warning "[Coverage Logger] No coverage.opencover.xml found. Run tests with --collect:'XPlat Code Coverage' first."
    exit 0
}

# Use the most recently modified file
$xmlFile = $xmlFiles | Sort-Object LastWriteTime -Descending | Select-Object -First 1

Write-Host "[Coverage Logger] Parsing: $($xmlFile.FullName)"

# ── Parse OpenCover XML ───────────────────────────────────────────────────────
[xml]$xml = Get-Content $xmlFile.FullName -Encoding UTF8

$summary = $xml.CoverageSession.Summary

# OpenCover attributes
$lineRate      = if ($summary) { [double]$summary.sequenceCoverage } else { 0 }
$branchRate    = if ($summary) { [double]$summary.branchCoverage }   else { 0 }
$visitedClasses  = if ($summary) { [int]$summary.visitedClasses }    else { 0 }
$numClasses      = if ($summary) { [int]$summary.numClasses }        else { 0 }
$visitedMethods  = if ($summary) { [int]$summary.visitedMethods }    else { 0 }
$numMethods      = if ($summary) { [int]$summary.numMethods }        else { 0 }
$visitedSequencePoints = if ($summary) { [int]$summary.visitedSequencePoints } else { 0 }
$numSequencePoints     = if ($summary) { [int]$summary.numSequencePoints }     else { 0 }

$methodRate = if ($numMethods -gt 0) { [math]::Round(($visitedMethods / $numMethods) * 100, 2) } else { 0 }

# ── Determine pass/fail ───────────────────────────────────────────────────────
$threshold  = 90
$linePct    = [math]::Round($lineRate, 2)
$branchPct  = [math]::Round($branchRate, 2)
$status     = if ($linePct -ge $threshold -and $branchPct -ge $threshold -and $methodRate -ge $threshold) { "PASS" } else { "FAIL" }
$statusIcon = if ($status -eq "PASS") { "✅" } else { "❌" }
$timestamp  = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$runDate    = Get-Date -Format "yyyy-MM-dd"
$runTime    = Get-Date -Format "HH:mm:ss"

# ── Build log entry ───────────────────────────────────────────────────────────
$entry = @"

## $statusIcon $timestamp — $status

| Metric | Covered | Total | Percentage | Threshold |
|--------|---------|-------|------------|-----------|
| Lines (Sequence Points) | $visitedSequencePoints | $numSequencePoints | $($linePct)% | 90% |
| Branches | — | — | $($branchPct)% | 90% |
| Methods | $visitedMethods | $numMethods | $($methodRate)% | 90% |
| Classes | $visitedClasses | $numClasses | — | — |

- **Source**: ``$($xmlFile.FullName)``
- **Run at**: $timestamp

---
"@

# ── Write history log ─────────────────────────────────────────────────────────
New-Item -ItemType Directory -Force -Path (Split-Path $logFile) | Out-Null

if (-not (Test-Path $logFile)) {
    $header = @"
# Coverage History Log

> Auto-generated by ``scripts/log-coverage.ps1`` after every test run.
> Threshold: **90%** (line, branch, method)

---
"@
    Set-Content -Path $logFile -Value $header -Encoding UTF8
}

Add-Content -Path $logFile -Value $entry -Encoding UTF8

# ── Write latest summary (always overwritten) ─────────────────────────────────
$latest = @"
# Latest Coverage Summary

> Updated: $timestamp

| Metric | Value | Status |
|--------|-------|--------|
| Line Coverage | $($linePct)% | $(if ($linePct -ge $threshold) { "✅ PASS" } else { "❌ FAIL" }) |
| Branch Coverage | $($branchPct)% | $(if ($branchPct -ge $threshold) { "✅ PASS" } else { "❌ FAIL" }) |
| Method Coverage | $($methodRate)% | $(if ($methodRate -ge $threshold) { "✅ PASS" } else { "❌ FAIL" }) |
| Classes Visited | $visitedClasses / $numClasses | — |
| Methods Visited | $visitedMethods / $numMethods | — |
| Lines Visited | $visitedSequencePoints / $numSequencePoints | — |

**Overall: $statusIcon $status**
"@

Set-Content -Path $summaryFile -Value $latest -Encoding UTF8

# ── Console output ────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host " Coverage Report — $timestamp"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host "  Line Coverage   : $($linePct)%   $(if ($linePct -ge $threshold) { '✅' } else { '❌' })"
Write-Host "  Branch Coverage : $($branchPct)%   $(if ($branchPct -ge $threshold) { '✅' } else { '❌' })"
Write-Host "  Method Coverage : $($methodRate)%   $(if ($methodRate -ge $threshold) { '✅' } else { '❌' })"
Write-Host "  Overall Status  : $statusIcon $status"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host "  Log written to  : coverage-logs\coverage-history.md"
Write-Host "  Summary at      : coverage-logs\latest-summary.md"
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
Write-Host ""

if ($status -eq "FAIL") {
    Write-Warning "[Coverage Logger] Coverage is below the 90% threshold. Fix coverage gaps before merging."
    exit 1
}

exit 0
